### ISSUE TITLE
Dependencies conflict

### ISSUE THREAD

**Issue by andersonkoh96** [sarahcssiqueira/base-wp-theme#6]
Hi there,

I'm new to mordern js + webpack development in WordPres, had no experience in node.js or composer. Is always done with page builder to build my page.

Just yesterday read your post here: https://dev.to/sarahcssiqueira/a-webpackconfigjs-for-wordpress-projects-2d68 and I feels like want to give it at try for my project.

I'm using Local Site as my local development and has meet your requirements or higher and used your theme as my boilerplate but I have some issue while running `npm install`. 

So I try to understand what happening is that "@wordpress/stylelint-config": "^21.20.0" required version of styleline@^14.16.1 instead my package.jason provided stylelint@ ^15.10.1 where the conflicts happened? What can we do to fix that, we adjust the @wordpress/stylelint-config version? Correct me if I'm wrong.

I can use npm install --legacy--peer-deps but I no sure will cause more problem later.

```bash
'Log files:
/Users/sensored/.npm/_logs/2024-07-07T05_06_24_715Z-debug-0.log

# npm resolution error report

While resolving: @wordpress/stylelint-config@21.20.0
Found: stylelint@15.10.1
node_modules/stylelint
  dev stylelint@"^15.10.1" from the root project
  peer stylelint@"^14.5.1 || ^15.0.0" from stylelint-scss@4.7.0
  node_modules/@wordpress/stylelint-config/node_modules/stylelint-scss
    stylelint-scss@"^4.0.0" from stylelint-config-recommended-scss@5.0.2
    node_modules/@wordpress/stylelint-config/node_modules/stylelint-config-recommended-scss
      stylelint-config-recommended-scss@"^5.0.2" from @wordpress/stylelint-config@21.20.0
      node_modules/@wordpress/stylelint-config
        dev @wordpress/stylelint-config@"^21.20.0" from the root project
  peer stylelint@"^15.10.0" from stylelint-config-recommended@13.0.0
  node_modules/stylelint-config-recommended
    stylelint-config-recommended@"^13.0.0" from stylelint-config-standard@34.0.0
    node_modules/stylelint-config-standard
      dev stylelint-config-standard@"^34.0.0" from the root project
  peer stylelint@"^15.5.0" from stylelint-config-recommended-scss@12.0.0
  node_modules/stylelint-config-recommended-scss
    stylelint-config-recommended-scss@"^12.0.0" from stylelint-config-standard-scss@10.0.0
    node_modules/stylelint-config-standard-scss
      dev stylelint-config-standard-scss@"^10.0.0" from the root project
  peer stylelint@"^15.5.0" from stylelint-config-recommended@12.0.0
  node_modules/stylelint-config-recommended-scss/node_modules/stylelint-config-recommended
    stylelint-config-recommended@"^12.0.0" from stylelint-config-recommended-scss@12.0.0
    node_modules/stylelint-config-recommended-scss
      stylelint-config-recommended-scss@"^12.0.0" from stylelint-config-standard-scss@10.0.0
      node_modules/stylelint-config-standard-scss
        dev stylelint-config-standard-scss@"^10.0.0" from the root project
  peer stylelint@"^15.10.0" from stylelint-config-standard@34.0.0
  node_modules/stylelint-config-standard
    dev stylelint-config-standard@"^34.0.0" from the root project
  peer stylelint@"^15.5.0" from stylelint-config-standard-scss@10.0.0
  node_modules/stylelint-config-standard-scss
    dev stylelint-config-standard-scss@"^10.0.0" from the root project
  peer stylelint@"^15.5.0" from stylelint-config-recommended@12.0.0
  node_modules/stylelint-config-standard-scss/node_modules/stylelint-config-recommended
    stylelint-config-recommended@"^12.0.0" from stylelint-config-standard@33.0.0
    node_modules/stylelint-config-standard-scss/node_modules/stylelint-config-standard
      stylelint-config-standard@"^33.0.0" from stylelint-config-standard-scss@10.0.0
      node_modules/stylelint-config-standard-scss
        dev stylelint-config-standard-scss@"^10.0.0" from the root project
  peer stylelint@"^15.5.0" from stylelint-config-standard@33.0.0
  node_modules/stylelint-config-standard-scss/node_modules/stylelint-config-standard
    stylelint-config-standard@"^33.0.0" from stylelint-config-standard-scss@10.0.0
    node_modules/stylelint-config-standard-scss
      dev stylelint-config-standard-scss@"^10.0.0" from the root project
  peer stylelint@"^14.5.1 || ^15.0.0" from stylelint-scss@5.0.1
  node_modules/stylelint-scss
    stylelint-scss@"^5.0.0" from stylelint-config-recommended-scss@12.0.0
    node_modules/stylelint-config-recommended-scss
      stylelint-config-recommended-scss@"^12.0.0" from stylelint-config-standard-scss@10.0.0
      node_modules/stylelint-config-standard-scss
        dev stylelint-config-standard-scss@"^10.0.0" from the root project
  peer stylelint@"^13.0.0 || ^14.0.0 || ^15.0.0" from stylelint-webpack-plugin@4.1.1
  node_modules/stylelint-webpack-plugin
    dev stylelint-webpack-plugin@"^4.1.1" from the root project

Could not resolve dependency:
peer stylelint@"^14.2" from @wordpress/stylelint-config@21.20.0
node_modules/@wordpress/stylelint-config
  dev @wordpress/stylelint-config@"^21.20.0" from the root project

Conflicting peer dependency: stylelint@14.16.1
node_modules/stylelint
  peer stylelint@"^14.2" from @wordpress/stylelint-config@21.20.0
  node_modules/@wordpress/stylelint-config
    dev @wordpress/stylelint-config@"^21.20.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by sarahcssiqueira** [comment]
Hi @andersonkoh96,

Sorry for the late response and glad my article helped you somehow. I tested the project on my machine and the things is, the error you are facing running `npm install ` indicates that @wordpress/stylelint-config@21.20.0 has a peer dependency requirement of stylelint@"^14.2", which conflicts with the installed version stylelint@15.10.1.

## Breaking further on steps:

### Root

These are the dependencies defined on package.json:

- stylelint@15.10.1
- @wordpress/stylelint-config@21.20.0

However, @wordpress/stylelint-config@21.20.0 requires stylelint@"^14.2", **causing the conflict**. We can't downgrade the stylelint@15.10.1 defined on root, as several other packages depends on it. See:

### Packages dependent on the root project stylelint@15.10.1:

- stylelint-scss@4.7.0 (peer stylelint@"^14.5.1 || ^15.0.0")
- stylelint-config-recommended-scss@5.0.2
- stylelint-config-recommended@13.0.0 (peer stylelint@"^15.10.0")
- stylelint-config-recommended-scss@12.0.0 (peer stylelint@"^15.5.0")
- stylelint-config-standard@34.0.0 (peer stylelint@"^15.10.0")
- stylelint-config-standard-scss@10.0.0 (peer stylelint@"^15.5.0")
- stylelint-scss@5.0.1 (peer stylelint@"^14.5.1 || ^15.0.0")
- stylelint-webpack-plugin@4.1.1 (peer stylelint@"^13.0.0 || ^14.0.0 || ^15.0.0")

I also can't update @wordpress/stylelint-config as I didn't find a newer version which supports stylelint@15.x.x.

### Resolution

That said, my plan to solve this is by adding an overrides section in the package.json 

```
"overrides": {
    "@wordpress/stylelint-config": {
      "stylelint": "^15.10.1"
        }
    }  

```

This will force @wordpress/stylelint-config to use stylelint@^15.10.1, ensuring compatibility with the rest of the project dependencies. This helps to align the peer dependency requirements without downgrading or force-installing packages with something like `npm install --legacy--peer-deps`.

Also, another idea, if you have enough time and want to dig deeper, you can also fork or modify the [@wordpress/stylelint-config](https://www.npmjs.com/package/@wordpress/stylelint-config) and modify its peer dependency to support stylelint@15.10.1.
        
And as you mentioned not having much experience with node.js or composer, @andersonkoh96, well, welcome to ["dependency hell"](https://www.boldare.com/blog/software-dependency-hell-what-is-it-and-how-to-avoid-it/) LOL


P.S: I am gonna to prepare a PR with the `overrides` section on package.json to close this issue tomorrow :)

**Comment by sarahcssiqueira** [comment]
Hello @andersonkoh96,

This is the [PR fixing the issue](https://github.com/sarahcssiqueira/base-wp-theme/pull/7) reported. Please, note that, for **Node.js >= 20**, you may encounter _**Unsupported engine**_ warnings because some dependencies do not yet support version ^20.0.0. If you are using NVM, you can switch to Node.js ^19.0.0 to avoid these warnings.

Thanks for letting me know about that!
